master:
  node_id: 1
  driver: "ros2_canopen::LifecycleMasterNode"
  package: "canopen_core"

proxy_device_1:
  node_id: 2
  dcf: "simple.eds"
  dcf_path: "install/canopen_tests/share/canopen_tests/config/simple"
  driver: "ros2_canopen::LifecycleProxyDriver"
  package: "canopen_proxy_driver"
  enable_lazy_load: false

proxy_device_2:
  node_id: 3
  dcf: "simple.eds"
  dcf_path: "install/canopen_tests/share/canopen_tests/config/simple"
  driver: "ros2_canopen::LifecycleProxyDriver"
  package: "canopen_proxy_driver"
  enable_lazy_load: true